# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd4bfc651470cc9e1a310a3fb6d1fde146f045a909a7331d918aa0d5ab0b219881dd3c0d3129e21fcd6c82a38d7e71f17929ae8dfa14f6344dc714e1bbd1bff4

test:
  secret_key_base: 5335c6f818315e95a893400198ba9988e6d891fc3f1576b7144267ce3cc4eabe39c077f9377dbc2a321ed7a2442ae6c5056461ebe5571c1e83d085bf3ae52968

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
